services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: .
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATASET_URL=https://api.nobelprize.org/v1/prize.json
    restart: always

volumes:
  mongo_data:
    driver: local
